service: lambda
provider:
  name: aws
  runtime: java11
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rds-data:ExecuteStatement"
      Resource: "arn:aws:rds-db:REGION:ACCOUNT_ID:dbuser:DATABASE_NAME/*"
functions:
  getAllUsers:
    handler: com.prueba.tecnica.backend.controllers::handleRequest
    events:
